  # Path for the classifier.
- classifier_file_name: gg-13-8-99-515-806-nb-classifier.qza

  # Qiime2 environment name.
  env: qiime2-2022.11

  # File path for the log file.
  logger_path: data_engineering_2.log

  # Logging level for the logger (CRITICAL, ERROR, WARNING, INFO, DEBUG, or NOTSET)
  logging_level: INFO


